### ISSUE TITLE
SKIP_ Checks = 1 does not take effect

### ISSUE THREAD

**Issue by wpf19950321** [oVirt/ovirt-node-ng#9]
Modify skip_ Checks = 1 does not take effect and chcek is still executed. How can I skip check?

**Comment by ghost** [comment]
It is not clear what exactly you are doing where and what you mean with `skip_ Checks`. Could you please specify:

* What you are trying to do in which context
* How you are trying to do it (which OS, which files/parameters you're changing, etc.)

Thank you!

**Comment by sandrobonazzola** [comment]
Closing with insufficient data. If you can provide needed info feel free to reopen.
